'''
This module contains the core game logic for a pipe-connecting puzzle game.
DO NOT EDIT THIS FILE DIRECTLY.
'''

from enum import Enum, auto
from random import randint
class Direction(Enum):
    """Enum representing the four cardinal directions for pipe openings: 

    - UP (facing North)
    - DOWN (facing South)
    - LEFT (facing West)
    - RIGHT (facing East)"""
    UP = auto()
    DOWN = auto()
    LEFT = auto()
    RIGHT = auto()
class PipeType(Enum):
    """Enum representing special types of pipes: 

    - SOURCE (where water starts) 
    - SINK (where water should end)."""
    SOURCE = auto()
    SINK = auto()
class Pipe:
    """Class representing a single pipe in the game.

    Available methods:
    - rotate(): Rotate the pipe 90 degrees clockwise.
    - connected(other_pipe, direction): Check if this pipe is connected to another pipe in the given direction.
    - get_openings(): Get the current openings of the pipe.
    - is_filled(): Check if the pipe is currently filled with water.
    - get_type(): Get the type of the pipe (SOURCE, SINK, or None).
    - get_position(): Get the current position of the pipe on the map."""
    def __init__(self, openings:tuple[Direction], pipe_type:PipeType | None, filled:bool=False):
        self.__openings = openings  # A set of Direction enums
        self.__pipe_type = pipe_type  # A PipeType enum
        self._filled = filled  # Whether the pipe is currently filled with water
        self._map:Map=None  # Reference to the map it belongs to, set when placed on the map
        self._position:tuple[int, int]=None  # Position on the map, set when placed on the map
    def rotate(self) -> None:
        """Rotate the pipe 90 degrees clockwise."""
        new_openings = []
        for direction in self.__openings:
            if direction == Direction.UP:
                new_openings.append(Direction.RIGHT)
            elif direction == Direction.RIGHT:
                new_openings.append(Direction.DOWN)
            elif direction == Direction.DOWN:
                new_openings.append(Direction.LEFT)
            elif direction == Direction.LEFT:
                new_openings.append(Direction.UP)
        self.__openings = tuple(new_openings)
        if self._map:
            self._map._update_water_flow()  # Update water flow after rotation

    def connected(self, other_pipe:'Pipe', direction:Direction) -> bool:
        """Check if this pipe is connected to another pipe in the given direction.

        @param other_pipe: The pipe to check connection with
        @param direction: The direction from this pipe to the other pipe
        @return: True if connected, False otherwise"""
        def opposite_direction(direction):
            OPPOSITE_MAP = {
                Direction.UP: Direction.DOWN,
                Direction.DOWN: Direction.UP,
                Direction.LEFT: Direction.RIGHT,
                Direction.RIGHT: Direction.LEFT
            }
            return OPPOSITE_MAP[direction]
            
        if direction in self.__openings and opposite_direction(direction) in other_pipe.__openings:
            return True
        return False
    
    def get_openings(self) -> tuple[Direction]:
        """Get the current openings of the pipe.

        @return: A tuple of Direction enums representing the openings."""
        return self.__openings
    def is_filled(self) -> bool:
        """Check if the pipe is currently filled with water.

        @return: True if filled, False otherwise"""
        return self._filled
    def get_type(self) -> PipeType | None:
        """Get the type of the pipe.

        @return: A PipeType enum representing the type of the pipe, or None if it's a regular pipe."""
        return self.__pipe_type
    def get_position(self) -> tuple[int, int]:
        """Get the current position of the pipe on the map.

        @return: A tuple (x, y) representing the position of the pipe on the map."""
        return self._position
    def get_adjacent_pipes(self) -> dict[Direction, 'Pipe']:
        """Get the adjacent pipes to this pipe on the map.

        @return: A dictionary mapping Direction enums to the adjacent Pipe objects (or None if no pipe in that direction)"""
        if self._map and self._position:
            x, y = self._position
            return self._map.get_adjacent_pipes(x, y)
        return {}
    
class Map:
    """Class representing the game map, which is a grid of pipes.

    Available methods:
    - load_grid(grid): Load a grid of pipes into the map.
    - get_pipe(x, y): Get the pipe at the specified coordinates.
    - rotate_pipe(x, y): Rotate the pipe at the specified coordinates.
    - get_adjacent_pipes(x, y): Get the adjacent pipes to the pipe at the specified coordinates.
    - __iter__(): Iterate over all pipes in the map."""
    def __init__(self, width:int, height:int):
        self.width = width
        self.height = height
        self.grid = [[None for _ in range(width)] for _ in range(height)]  # 2D grid of pipes
    @classmethod
    def load_grid(cls, grid:list[list[Pipe]]) -> 'Map':
        """Load a grid of pipes into the map.

        @param grid: A 2D list of Pipe objects representing the initial layout of the map.
        @return: An instance of Map with the grid loaded."""
        width = len(grid) 
        height = len(grid[0])if width > 0 else 0
        map_instance = cls(width, height)
        for x in range(width):
            for y in range(height):
                pipe = grid[x][y]
                if pipe:
                    map_instance._place_pipe(x, y, pipe)
        return map_instance
    
    def get_map_size(self) -> tuple[int, int]:
        """Get the size of the map.

        @return: A tuple (width, height) representing the size of the map."""
        return self.width, self.height
    
    def _place_pipe(self, x:int, y:int, pipe:Pipe):
        self.grid[x][y] = pipe
        pipe._map = self  # Set the map reference in the pipe
        pipe._position = (x, y)  # Set the position reference in the pipe
        pipe._filled = False  # Ensure the pipe starts as unfilled
    def get_pipe(self, x:int, y:int) -> Pipe:
        """Get the pipe at the specified coordinates.

        @param x: The x-coordinate of the pipe
        @param y: The y-coordinate of the pipe
        @return: The Pipe object at the specified coordinates, or None if there is no pipe."""
        if 0 <= x < self.width and 0 <= y < self.height:
            return self.grid[x][y]
        raise IndexError("Coordinates out of bounds")
    def rotate_pipe(self, x:int, y:int) -> None:
        """Rotate the pipe at the specified coordinates.

        @param x: The x-coordinate of the pipe to rotate
        @param y: The y-coordinate of the pipe to rotate
        """
        pipe = self.get_pipe(x, y)
        if pipe:
            pipe.rotate()
    
    def get_adjacent_pipes(self, x:int, y:int)-> dict[Direction, Pipe]:
        """Get the adjacent pipes to the pipe at the specified coordinates.

        @param x: The x-coordinate of the pipe
        @param y: The y-coordinate of the pipe
        @return: A dictionary mapping Direction enums to the adjacent Pipe objects (or None if no pipe in that direction)"""
        adjacent = {}
        if y < self.height - 1:  
            adjacent[Direction.DOWN] = self.get_pipe(x, y+1)
        if y > 0:  
            adjacent[Direction.UP] = self.get_pipe(x, y-1)
        if x > 0:  # Left
            adjacent[Direction.LEFT] = self.get_pipe(x-1, y)
        if x < self.width - 1:  # Right
            adjacent[Direction.RIGHT] = self.get_pipe(x+1, y)
        return adjacent
    def _update_water_flow(self):
        # This method would contain the logic to update the water flow through the pipes
        # It would check for connected pipes and fill them accordingly
        for pipe in self:
            pipe._filled = False  # Reset all pipes to unfilled

        queue:list[Pipe]=[]
        for pipe in self:
            if pipe.get_type() == PipeType.SOURCE:
                pipe._filled = True
                queue.append(pipe)

        while queue:
            current_pipe = queue.pop(0)
            x,y = current_pipe.get_position()
            for direction, adjacent_pipe in self.get_adjacent_pipes(x,y).items():
                direction:Direction
                adjacent_pipe:Pipe
                
                if adjacent_pipe and current_pipe.connected(adjacent_pipe, direction) and not adjacent_pipe._filled:
                    adjacent_pipe._filled = True
                    queue.append(adjacent_pipe)
        
    def __iter__(self):
        """**EXAMPLE USAGE:**

        *for pipe in game_map:*
            *print pipe.get_position()*
        """
        for x in range(self.width):
            for y in range(self.height):
                yield self.get_pipe(x, y)
    
class PipeGenerator: 
    @classmethod
    def sink(cls):
        pipe= Pipe(openings=(Direction.UP,), pipe_type=PipeType.SINK)
        for _ in range(randint(0, 3)):
            pipe.rotate()
        return pipe
    @classmethod
    def corner(cls, is_source:bool=False):
        pipe= Pipe(
            openings=(Direction.UP, Direction.RIGHT), 
            pipe_type=PipeType.SOURCE if is_source else None, 
            filled=is_source)
        for _ in range(randint(0, 3)):
            pipe.rotate()
        return pipe
    @classmethod
    def straight(cls, is_source:bool=False):
        pipe= Pipe(
            openings=(Direction.UP, Direction.DOWN), 
            pipe_type=PipeType.SOURCE if is_source else None, 
            filled=is_source)
        for _ in range(randint(0, 3)):
            pipe.rotate()
        return pipe
    @classmethod
    def t(cls, is_source:bool=False):
        pipe= Pipe(
            openings=(Direction.UP, Direction.LEFT, Direction.RIGHT), 
            pipe_type=PipeType.SOURCE if is_source else None, 
            filled=is_source)
        for _ in range(randint(0, 3)):
            pipe.rotate()
        return pipe
    @classmethod
    def cross(cls, is_source:bool=False):
        pipe= Pipe(
            openings=(Direction.UP, Direction.DOWN, Direction.LEFT, Direction.RIGHT), 
            pipe_type=PipeType.SOURCE if is_source else None, 
            filled=is_source)
        for _ in range(randint(0, 3)):
            pipe.rotate()
        return pipe

class MapGenerator:
    @classmethod
    def default_map(cls) -> Map:
        map=Map.load_grid([
                [PipeGenerator.sink(), PipeGenerator.corner(), PipeGenerator.corner(), PipeGenerator.sink()],
                [PipeGenerator.corner(), PipeGenerator.t(), PipeGenerator.t(), PipeGenerator.corner()],
                [PipeGenerator.sink(), PipeGenerator.t(), PipeGenerator.corner(True), PipeGenerator.straight()],
                [PipeGenerator.sink(), PipeGenerator.corner(), PipeGenerator.sink(), PipeGenerator.corner()],
            ])
        map._update_water_flow()
        return map
        

if __name__ == "__main__":
    map = MapGenerator.default_map()
    for pipe in map:
        print(pipe.get_position(), pipe.get_openings(), pipe.get_type(), pipe.is_filled())